### ISSUE TITLE
Getting an error when webpack is running

### ISSUE THREAD

**Issue by johndobrien** [neroniaky/angular2-token-example#5]
I'm very sorry as I should be able to figure this out, but I am getting the error below when trying to run the postinstall...

```
webpack --inline --colors --progress --display-error-details --display-cached

 90% optimize assetsError: Debug Failure. False expression: File  has unknown extension.
    at Object.assert (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:3177:23)
    at Object.fail (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:3182:19)
    at Object.extensionFromPath (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:3324:15)
    at /Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:62182:46
    at Array.map (native)
    at resolveModuleNamesWorker (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:62176:141)
    at resolveModuleNamesReusingOldState (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:62300:24)
    at processImportedModules (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:63152:35)
    at findSourceFile (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:63062:17)
    at processSourceFile (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:62965:27)
    at processRootFile (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:62852:13)
    at /Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:62203:60
    at Object.forEach (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:1294:30)
    at Object.createProgram (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:62203:16)
    at synchronizeHostData (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:78867:33)
    at Object.getProgram (/Users/john/pda/pda-vnext/angular2-client/node_modules/typescript/lib/typescript.js:78967:13)
    at State.updateProgram (/Users/john/pda/pda-vnext/angular2-client/node_modules/awesome-typescript-loader/dist.babel/host.js:241:42)
    at /Users/john/pda/pda-vnext/angular2-client/node_modules/awesome-typescript-loader/dist.babel/instance.js:333:27
    at Compiler.<anonymous> (/Users/john/pda/pda-vnext/angular2-client/node_modules/awesome-typescript-loader/dist.babel/instance.js:354:15)
    at Compiler.next (/Users/john/pda/pda-vnext/angular2-client/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/john/pda/pda-vnext/angular2-client/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/john/pda/pda-vnext/angular2-client/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/john/pda/pda-vnext/angular2-client/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/john/pda/pda-vnext/angular2-client/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.next (/Users/john/pda/pda-vnext/angular2-client/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Users/john/pda/pda-vnext/angular2-client/node_modules/webpack/lib/ProgressPlugin.js:69:5)
    at Compilation.applyPluginsAsync (/Users/john/pda/pda-vnext/angular2-client/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/john/pda/pda-vnext/angular2-client/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.next (/Users/john/pda/pda-vnext/angular2-client/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Users/john/pda/pda-vnext/angular2-client/node_modules/webpack/lib/ProgressPlugin.js:65:5)
```

**Comment by neroniaky** [comment]
This example has been merged into the main repository. Please refer to https://github.com/neroniaky/angular-token if you have any questions. Thanks!
